# Generated by Django 6.0.2 on 2026-03-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calory', '0006_rename_category_food_meal_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='streak_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
